// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiV-NK0xbRwYJXEBsatanqP9dPCv6BMVE',
    appId: '1:298419835115:web:9a99d57b3f5c1055802eae',
    messagingSenderId: '298419835115',
    projectId: 'civicsync-f6509',
    authDomain: 'civicsync-f6509.firebaseapp.com',
    storageBucket: 'civicsync-f6509.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHV-GhDt_2_WL9032n9RXDF-EDLY5XdOk',
    appId: '1:298419835115:android:cd43dd9f48943fdc802eae',
    messagingSenderId: '298419835115',
    projectId: 'civicsync-f6509',
    storageBucket: 'civicsync-f6509.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHwPzmdcwHjZg2lkjA94piM1cIJNhLbQ8',
    appId: '1:298419835115:ios:18fc6b58eaace9ed802eae',
    messagingSenderId: '298419835115',
    projectId: 'civicsync-f6509',
    storageBucket: 'civicsync-f6509.firebasestorage.app',
    iosBundleId: 'com.example.civicsync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHwPzmdcwHjZg2lkjA94piM1cIJNhLbQ8',
    appId: '1:298419835115:ios:18fc6b58eaace9ed802eae',
    messagingSenderId: '298419835115',
    projectId: 'civicsync-f6509',
    storageBucket: 'civicsync-f6509.firebasestorage.app',
    iosBundleId: 'com.example.civicsync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiV-NK0xbRwYJXEBsatanqP9dPCv6BMVE',
    appId: '1:298419835115:web:20d16fb7d4b8a4c6802eae',
    messagingSenderId: '298419835115',
    projectId: 'civicsync-f6509',
    authDomain: 'civicsync-f6509.firebaseapp.com',
    storageBucket: 'civicsync-f6509.firebasestorage.app',
  );
}
